// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	share3 "github.com/WindyDante/toolpost/internal/handler/share"
	"github.com/WindyDante/toolpost/internal/repository/share"
	share2 "github.com/WindyDante/toolpost/internal/service/share"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuildHandler(db *gorm.DB) (*Handlers, error) {
	shareRepositoryInterface := share.NewShareRepository(db)
	shareServiceInterface := share2.NewShareService(shareRepositoryInterface)
	shareHandler := share3.NewShareHandler(shareServiceInterface)
	handlers := NewHandlers(shareHandler)
	return handlers, nil
}

// wire.go:

var ShareSet = wire.NewSet(share.NewShareRepository, share2.NewShareService, share3.NewShareHandler)
